# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'denizzzzp/pipelines-javascript-docker'

steps:



- task: Docker@2
  displayName: Docker HUB login
  inputs:
    containerRegistry: 'denizzzzp-hub'
    command: 'login'
- task: Docker@2
  displayName: Build an push image
  inputs:
    containerRegistry: 'denizzzzp-hub'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)